# Generated by Django 2.2.3 on 2019-07-08 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_To_Vendor_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.CharField(max_length=100)),
                ('direction', models.BooleanField(default=True)),
                ('high_priority', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_To_Vendor_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.CharField(max_length=100, verbose_name='Order Details')),
                ('direction', models.BooleanField(default=True)),
                ('high_priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AddField(
            model_name='hospital',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_document',
            field=models.FileField(default=None, null=True, upload_to='hospital documents'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Hospital Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_no',
            field=phone_field.models.PhoneField(default='0000000000', max_length=31, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='Medicine_name',
            field=models.CharField(default='', max_length=30, verbose_name='Medicine Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='Medicine_type',
            field=models.CharField(choices=[('Schedule 1', 'Schedule 1'), ('Schedule 2', 'Schedule 2'), ('Schedule 3', 'Schedule 3'), ('Schedule 4', 'Schedule 4'), ('Schedule 5', 'Schedule 5')], default='', max_length=50, verbose_name='Type of Medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='vendor_selling',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normal_user',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normal_user',
            name='phone_no',
            field=phone_field.models.PhoneField(default='000000000', max_length=31, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_no',
            field=phone_field.models.PhoneField(default='0000000000', max_length=31, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_verification_document',
            field=models.FileField(default=None, upload_to='license_documents', verbose_name='Vendor License'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Medicine_dosage',
            field=models.IntegerField(verbose_name='Dosage in Milligram(mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Medicine_price',
            field=models.FloatField(verbose_name='Cost Of The Medicine'),
        ),
        migrations.AddField(
            model_name='user_to_vendor_order',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Normal_User'),
        ),
        migrations.AddField(
            model_name='user_to_vendor_order',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Vendor'),
        ),
        migrations.AddField(
            model_name='hospital_to_vendor_order',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Hospital'),
        ),
        migrations.AddField(
            model_name='hospital_to_vendor_order',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Vendor'),
        ),
    ]
