# Generated by Django 2.2.3 on 2019-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_vendor_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50, verbose_name='Vendor Name')),
                ('medicine_name', models.CharField(max_length=50, verbose_name='Medicine Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity Of Medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity Of Medicine in Stock'),
            preserve_default=False,
        ),
    ]
