# Generated by Django 2.2.3 on 2019-07-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190710_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_to_vendor_order',
            name='order_details',
            field=models.CharField(max_length=1000, verbose_name='Order Details'),
        ),
        migrations.AlterField(
            model_name='user_to_vendor_order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Normal_User'),
        ),
        migrations.AlterField(
            model_name='user_to_vendor_order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Vendor'),
        ),
    ]
