# Generated by Django 2.2.3 on 2019-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190711_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_to_vendor_order',
            name='order_details',
            field=models.CharField(max_length=100, verbose_name='Order Details'),
        ),
    ]
