# Generated by Django 2.2.3 on 2019-07-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190711_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_to_vendor_order',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospital_to_vendor_order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Vendor'),
        ),
    ]
